version: "3.3"

services:
  sentinel:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/usr/src/sentinel/node_modules
      - next:/usr/src/sentinel/.next
volumes:
  node_modules:
  next: